# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec6c5b1a15f673fa025958f99b909f1bad3f57efc19d0e7621ac3f6761eb7c7ef0c283e486b70336d9c21c65428ea1f812d38e6a261017c5094cec44eee26819

test:
  secret_key_base: b11db16b722a6054de6ec53ee40e7f1c0e146585cb554e5564ada8818fcea0c5aba2bbb6370efe6417ca4d9e9d560271bc0427748165f91fd293b1db9fd9dea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
