# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53636253e438b8ef0f062820dca815f195fceeef020501c6afe7fba45adf72044fd0276f6d18bdec8feb3456e33106219d6b7e4050b1e8e0edc89dfa5c5ce0c0

test:
  secret_key_base: 629154603d5ac02808e13b482e7bfd02428acbf16e1aeb77b38b7faffe08ff9d0c6a06aceea16f0a5c36d282c15b25c022b5d305747621b6196dad44e71c36b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
